routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });


Route::get('/product-list/{id?}', 'WebpageController@product_list');

Route::get('/product-detail/{id}', 'WebpageController@product_detail');

Route::post('/product-filter', 'WebpageController@product_filter');

Route::post('/product-view-all', 'WebpageController@product_view_all');

Route::get('/product-price-filter', 'WebpageController@product_price_filter');


Route::get('/about-us', 'WebpageController@about_us');

Route::get('/contact-us', 'WebpageController@contact_us');

Route::post('/sendingemail', 'WebpageController@sendEmail');

Route::get('/promotion', 'WebpageController@promotion');

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);

    Route::resource('collection', 'Admin\CollectionController');

    Route::resource('product', 'Admin\ProductController');

    Route::get('delete_image/{image_id}/{product_id}', 'Admin\ProductController@deleteImage');

    Route::resource('about', 'Admin\AboutController');

    Route::resource('promotion', 'Admin\PromotionController');

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public function images(){
    	return $this->hasMany('App\ProductImage');
    }

    public function category(){
    	return $this->belongsTo('App\Collection');
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Product;
use App\Collection;
use App\ProductImage;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\Admin\ProductRequest;


class ProductController extends Controller
{
	public function index(){

		$products = Product::all();
		return view('admin.product.index', compact(['products']));
	}

	public function create(){
		$categories = Collection::pluck('name', 'id');

		return view('admin.product.create', compact(['categories']));
	}

	public function store(ProductRequest $request){

		$product = new Product();
		$product->name = $request->name;

		if ($request->main_image != null) {

            $files = $request->main_image;
            $file_path = date("M-Y");
            $destinationPath =app()->make('path.public');
            $image_path = '/uploads/products/'.$file_path;
            $filename= str_random(3).'cover_'.$files->getClientOriginalName();
            $files->move($destinationPath.$image_path, $filename);            

            $product->image_name = $filename;
            $product->image_path = $image_path;
        }
		
		$product->category_id = $request->category_id;
		$product->price = $request->price;
		$product->description = $request->description;
		$product->technical = $request->technical;
		$product->question = $request->question;
		$product->save();

		for($i=0; $i<count($request->other_image); $i++){

			$productImage = new ProductImage();
			$productImage->product_id = $product->id;

			if ($request->other_image[$i] != null) {

	            $files = $request->other_image[$i];
	            $file_path = date("M-Y");
	            $destinationPath =app()->make('path.public');
	            $image_path = '/uploads/products/'.$file_path;
	            $filename= str_random(3).'cover_'.$files->getClientOriginalName();
	            $files->move($destinationPath.$image_path, $filename);     

	            $productImage->image_name = $filename;
            	$productImage->image_path = $image_path;

	        }
			
			$productImage->save();
		}


		return redirect()->route('admin.product.index');
	}


	public function edit($id){

		$product = Product::findOrFail($id);
		$categories = Collection::pluck('name', 'id');
		$product_image = ProductImage::where('product_id',$id)->get();

		return view('admin.product.edit', compact(['categories','product','product_image']));
	}

	public function update(ProductRequest $request,$id){
		$product = Product::find($id);
		$product->name = $request->name;

		if ($request->main_image != null) {

            $files = $request->main_image;
            $file_path = date("M-Y");
            $destinationPath =app()->make('path.public');
            $image_path = '/uploads/products/'.$file_path;
            $filename= str_random(3).'cover_'.$files->getClientOriginalName();
            $files->move($destinationPath.$image_path, $filename);          

            $product->image_name = $filename;
            $product->image_path = $image_path;
        }
		
		$product->category_id = $request->category_id;
		$product->price = $request->price;
		$product->description = $request->description;
		$product->technical = $request->technical;
		$product->question = $request->question;
		$product->save();
		
		//update existing image
		if($request->other_image != NULL){
			foreach($request->other_image as $key=>$value){
				$files = $value;
	            $file_path = date("M-Y");
	            $destinationPath =app()->make('path.public');
	            $image_path = '/uploads/products/'.$file_path;
	            $filename= str_random(3).'cover_'.$files->getClientOriginalName();
	            $files->move($destinationPath.$image_path, $filename);          

				ProductImage::where('id',$key)->update([
					'image_name' => $filename,
					'image_path' => $image_path
				]);
			}
			
		}

		//save new image
		if($request->other_new_image != NULL){
			foreach($request->other_new_image as $key=>$value){
				$files = $value;
	            $file_path = date("M-Y");
	            $destinationPath =app()->make('path.public');
	            $image_path = '/uploads/products/'.$file_path;
	            $filename= str_random(3).'cover_'.$files->getClientOriginalName();
	            $files->move($destinationPath.$image_path, $filename);

				ProductImage::create([
					'product_id' => $product->id,
					'image_name' => $filename,
					'image_path' => $image_path
				]);
			}
			
		}

		return redirect()->route('admin.product.index');
	}

	public function show($id){

		$product = Product::findOrFail($id);
		$categories = Collection::pluck('name', 'id');
		$product_image = ProductImage::where('product_id',$id)->get();

		return view('admin.product.view', compact(['categories','product','product_image']));
	}

	public function deleteImage($image_id,$product_id){

		ProductImage::where('id',$image_id)->where('product_id',$product_id)->delete();
		return "Ok";
	}

	public function destroy($id)
    {
        
        $product = Product::findOrFail($id);
        $product->delete();

        $product_image = ProductImage::where('product_id', $id)->delete();

        return redirect()->route('admin.product.index');
    }
}

resources/views/admin/product/create.blade.php
@extends('layouts.app')
@section('css')
<link rel="stylesheet" href="{{asset('/css/bootstrap-fileupload.min.css')}}" />
@endsection
@section('content')
    <h3 class="page-title">Product</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.product.store'], 'enctype' => 'multipart/form-data']) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    <div class="col-xs-3">
                        {!! Form::label('name', 'Name*', ['class' => 'control-label']) !!}
                    </div>
                    <div class="col-xs-6">
                        {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '']) !!}
                        <p class="help-block"></p>
                        @if($errors->has('name'))
                            <p class="help-block">
                                {{ $errors->first('name') }}
                            </p>
                        @endif
                    </div>
                </div>
                <div class="col-xs-12 form-group">
                    <div class="col-xs-3">
                        {!! Form::label('category', 'Category*', ['class' => 'control-label']) !!}
                    </div>
                    <div class="col-xs-6">
                        {!! Form::select('category_id', $categories, old('category_id'), ['class' => 'form-control select2']) !!}
                    </div>                    
                </div>
                <div class="col-xs-12 form-group">
                    <div class="col-xs-3">
                        {!! Form::label('price', 'Price*', ['class' => 'control-label']) !!}
                    </div>
                    <div class="col-xs-6">
                        {!! Form::text('price', old('price'), ['class' => 'form-control', 'placeholder' => '']) !!}
                        <p class="help-block"></p>
                        @if($errors->has('price'))
                            <p class="help-block">
                                {{ $errors->first('price') }}
                            </p>
                        @endif
                    </div>
                </div>
                <div class="col-xs-12 form-group">
                    <div class="col-xs-3">
                        {!! Form::label('description', 'Description*', ['class' => 'control-label']) !!}
                    </div>
                    <div class="col-xs-6">
                        {!! Form::textarea('description', old('description'), ['class' => 'form-control editor', 'placeholder' => '']) !!}
                        <p class="help-block"></p>
                        @if($errors->has('description'))
                            <p class="help-block">
                                {{ $errors->first('description') }}
                            </p>
                        @endif
                    </div>                   
                </div>
                <div class="col-xs-12 form-group">
                    <div class="col-xs-3">
                        {!! Form::label('technical', 'Technical Lowdown*', ['class' => 'control-label']) !!}
                    </div>
                    <div class="col-xs-6">
                        {!! Form::textarea('technical', old('technical'), ['class' => 'form-control editor', 'placeholder' => '']) !!}
                        <p class="help-block"></p>
                        @if($errors->has('technical'))
                            <p class="help-block">
                                {{ $errors->first('technical') }}
                            </p>
                        @endif
                    </div>
                </div>
                <div class="col-xs-12 form-group">
                    <div class="col-xs-3">
                        {!! Form::label('question', ' Question*', ['class' => 'control-label']) !!}
                    </div>
                    <div class="col-xs-6">
                        {!! Form::textarea('question', old('question'), ['class' => 'form-control editor', 'placeholder' => '']) !!}
                        <p class="help-block"></p>
                        @if($errors->has('question'))
                            <p class="help-block">
                                {{ $errors->first('question') }}
                            </p>
                        @endif
                    </div>
                </div>
                <div class="col-xs-12 form-group">
                    <div class="col-xs-3">
                        {!! Form::label('image', 'Main Image*', ['class' => 'control-label']) !!}
                    </div>
                    <div class="col-xs-6">
                        <div class="fileupload fileupload-new" data-provides="fileupload">
                            <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;"><img class="index-img" src=""/>
                            </div>
                            <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                            <div>
                                <span class="btn btn-file btn-primary">
                                    <span class="fileupload-new">Select image</span>
                                    <span class="fileupload-exists">Change</span>
                                    <input name="main_image" type="file" />
                                </span>
                                <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload">Remove</a>
                            </div>
                        </div>
                        <p class="help-block"></p>
                        @if($errors->has('main_image'))
                            <p class="help-block">
                                {{ $errors->first('main_image') }}
                            </p>
                        @endif
                    </div>                    
                </div>
                <br>
                <hr>
                <div class="form-group">
                    <div class="col-md-3">
                        <button type="button" onclick="addTeam()" class="btn btn-bg btn-info">Add Other Image</button>
                    </div>
                </div>

                <div id="team_wrap"></div>

            </div>
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

@section('javascript')
<script src="{{asset('/js/bootstrap-fileupload.js')}}"></script>
<script src="{{asset('/libs/ckeditor/ckeditor.js')}}"></script>

<script type="text/html" id="add_team_html">
  <div class="team">    
    <div class="col-xs-12 form-group">
        <div class="col-xs-3">            
        </div>
        <div class="col-xs-4">
            <div class="fileupload fileupload-new" data-provides="fileupload">
                <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;"><img class="index-img" src=""/>
                </div>
                <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                <div>
                    <span class="btn btn-file btn-primary">
                        <span class="fileupload-new">Select image</span>
                        <span class="fileupload-exists">Change</span>
                        <input name="other_image[]" type="file" />
                    </span>
                    <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload">Remove</a>
                </div>
            </div>
            <p class="help-block"></p>
            @if($errors->has('other_image'))
                <p class="help-block">
                    {{ $errors->first('other_image') }}
                </p>
            @endif
        </div>  
        <div class="col-md-1">
            <button type="button" class="btn btn-danger remove_team">
                <i class="fa fa-close"></i>
            </button>
        </div>                  
    </div>
    <hr>
</div>
</script>

<script>
    $(function () {
        CKEDITOR.replaceClass = 'editor';
    });

    addTeam();

    $("#team_wrap").on("click", ".remove_team", function(){
        $(this).parents('.team').remove();
    });

    function addTeam()
    {
        $('#team_wrap').append($('#add_team_html').html());
    }
</script>
@endsection

resources/views/admin/product/edit.blade.php
@extends('layouts.app')
@section('css')
<link rel="stylesheet" href="{{asset('/css/bootstrap-fileupload.min.css')}}" />
@endsection
@section('content')
    <h3 class="page-title">Product</h3>

    {!! Form::model($product, ['method' => 'PUT', 'route' => ['admin.product.update', $product->id], 'enctype' => 'multipart/form-data']) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_edit')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    <div class="col-xs-3">
                        {!! Form::label('name', 'Name*', ['class' => 'control-label']) !!}
                    </div>
                    <div class="col-xs-6">
                        {!! Form::text('name', $product->name, ['class' => 'form-control', 'placeholder' => '']) !!}
                        <p class="help-block"></p>
                        @if($errors->has('name'))
                            <p class="help-block">
                                {{ $errors->first('name') }}
                            </p>
                        @endif
                    </div>
                </div>
                <div class="col-xs-12 form-group">
                    <div class="col-xs-3">
                        {!! Form::label('category', 'Category*', ['class' => 'control-label']) !!}
                    </div>
                    <div class="col-xs-6">
                        {!! Form::select('category_id', $categories, $product->category->id, ['class' => 'form-control select2']) !!}
                    </div>                    
                </div>
                <div class="col-xs-12 form-group">
                    <div class="col-xs-3">
                        {!! Form::label('price', 'Price*', ['class' => 'control-label']) !!}
                    </div>
                    <div class="col-xs-6">
                        {!! Form::text('price', $product->price, ['class' => 'form-control', 'placeholder' => '']) !!}
                        <p class="help-block"></p>
                        @if($errors->has('price'))
                            <p class="help-block">
                                {{ $errors->first('price') }}
                            </p>
                        @endif
                    </div>
                </div>
                <div class="col-xs-12 form-group">
                    <div class="col-xs-3">
                        {!! Form::label('description', 'Description*', ['class' => 'control-label']) !!}
                    </div>
                    <div class="col-xs-6">
                        {!! Form::textarea('description', $product->description, ['class' => 'form-control editor', 'placeholder' => '']) !!}
                        <p class="help-block"></p>
                        @if($errors->has('description'))
                            <p class="help-block">
                                {{ $errors->first('description') }}
                            </p>
                        @endif
                    </div>                   
                </div>
                <div class="col-xs-12 form-group">
                    <div class="col-xs-3">
                        {!! Form::label('technical', 'Technical Lowdown*', ['class' => 'control-label']) !!}
                    </div>
                    <div class="col-xs-6">
                        {!! Form::textarea('technical', $product->technical, ['class' => 'form-control editor', 'placeholder' => '']) !!}
                        <p class="help-block"></p>
                        @if($errors->has('technical'))
                            <p class="help-block">
                                {{ $errors->first('technical') }}
                            </p>
                        @endif
                    </div>
                </div>
                <div class="col-xs-12 form-group">
                    <div class="col-xs-3">
                        {!! Form::label('question', ' Question*', ['class' => 'control-label']) !!}
                    </div>
                    <div class="col-xs-6">
                        {!! Form::textarea('question', $product->question, ['class' => 'form-control editor', 'placeholder' => '']) !!}
                        <p class="help-block"></p>
                        @if($errors->has('question'))
                            <p class="help-block">
                                {{ $errors->first('question') }}
                            </p>
                        @endif
                    </div>
                </div>
                <div class="col-xs-12 form-group">
                    <div class="col-xs-3">
                        {!! Form::label('image', 'Main Image*', ['class' => 'control-label']) !!}
                    </div>
                    <div class="col-xs-6">
                        <div class="fileupload fileupload-new" data-provides="fileupload">
                            <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;"><img class="index-img" src='{{asset("$product->image_path/$product->image_name")}}'/>
                            </div>
                            <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                            <div>
                                <span class="btn btn-file btn-primary">
                                    <span class="fileupload-new">Select image</span>
                                    <span class="fileupload-exists">Change</span>
                                    <input name="main_image" type="file" />
                                </span>
                                <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload">Remove</a>
                            </div>
                        </div>
                        <p class="help-block"></p>
                        @if($errors->has('main_image'))
                            <p class="help-block">
                                {{ $errors->first('main_image') }}
                            </p>
                        @endif
                    </div>                    
                </div>
                <br>
                <hr>
                <div class="form-group">
                    <div class="col-md-3">
                        <button type="button" onclick="addTeam()" class="btn btn-bg btn-info">Add Other Image</button>
                    </div>
                </div>

               
                
                <div id="team_wrap">
                    @foreach($product_image as $value)
                    <div class="team"> 
                    <div class="col-xs-12 form-group">
                        <div class="col-xs-3">
                        </div>
                        <div class="col-xs-4">
                            <div class="fileupload fileupload-new" data-provides="fileupload">
                                <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;"><img class="index-img" src='{{asset("$value->image_path/$value->image_name")}}'/>

                                </div>
                                <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                                <div>
                                    <span class="btn btn-file btn-primary">
                                        <span class="fileupload-new">Select image</span>
                                        <span class="fileupload-exists">Change</span>
                                        <input name="other_image[{{$value->id}}]" type="file" />
                                    </span>
                                    <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload">Remove</a>
                                </div>
                            </div>
                            <p class="help-block"></p>
                            @if($errors->has('other_image'))
                                <p class="help-block">
                                    {{ $errors->first('other_image') }}
                                </p>
                            @endif
                        </div>  
                        <div class="col-md-1">
                            <button type="button" class="btn btn-danger remove_team" image_id="{{$value->id}}" product_id="{{$product->id}}">
                                <i class="fa fa-close"></i>
                            </button>
                        </div>                  
                    </div>
                    </div>
                @endforeach
                </div>

            </div>
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

@section('javascript')
<script src="{{asset('/js/bootstrap-fileupload.js')}}"></script>
<script src="{{asset('/libs/ckeditor/ckeditor.js')}}"></script>

<script type="text/html" id="add_team_html">
    <div class="team">    
    <div class="col-xs-12 form-group">
        <div class="col-xs-3">            
        </div>
        <div class="col-xs-4">
            <div class="fileupload fileupload-new" data-provides="fileupload">
                <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;"><img class="index-img" src=""/>
                </div>
                <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                <div>
                    <span class="btn btn-file btn-primary">
                        <span class="fileupload-new">Select image</span>
                        <span class="fileupload-exists">Change</span>
                        <input name="other_new_image[]" type="file" />
                    </span>
                    <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload">Remove</a>
                </div>
            </div>
            <p class="help-block"></p>
            @if($errors->has('other_image'))
                <p class="help-block">
                    {{ $errors->first('other_image') }}
                </p>
            @endif
        </div>  
        <div class="col-md-1">
            <button type="button" class="btn btn-danger remove_team">
                <i class="fa fa-close"></i>
            </button>
        </div>                  
    </div>
    <hr>
</div>   
</script>

<script>
    $(function () {
        CKEDITOR.replaceClass = 'editor';
    });

    $("#team_wrap").on("click", ".remove_team", function(){
        $(this).parents('.team').remove();
    });

    function addTeam()
    {
        $('#team_wrap').append($('#add_team_html').html());
    }

    $('.remove_team').click(function(){
        var image_id    = $(this).attr('image_id');
        var product_id  = $(this).attr('product_id')
        
        $.ajax({
        type : 'GET',
        url : '/admin/delete_image/'+image_id+'/'+product_id,
        success :function(return_data){            
        }
    });
    });
</script>
@endsection

resources/views/admin/product/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">Product</h3>
    <p>
        <a href="{{ route('admin.product.create') }}" class="btn btn-success">Create</a>        
    </p>    

    <div class="panel panel-default">
        <div class="panel-heading">
            List
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($products) > 0 ? 'datatable' : '' }}">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Category</th>
                        <th>Price</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                
                <tbody>
                    @if (count($products) > 0)
                        @foreach ($products as $product)
                            <tr data-entry-id="{{ $product->id }}">
                                <td field-key='name'>{{ $product->name }}</td>
                                <td field-key='category'>{{ $product->category->name }}</td>
                                <td field-key='price'>{{ $product->price }}</td>
                                <td>
                                    <a href="{{ route('admin.product.show',[$product->id]) }}" class="btn btn-xs btn-primary">View</a>                                    
                                    <a href="{{ route('admin.product.edit',[$product->id]) }}" class="btn btn-xs btn-info">Edit</a>
									{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.product.destroy', $product->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                </td>

                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="10">@lang('quickadmin.qa_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('user_delete')
            window.route_mass_crud_entries_destroy = '{{ route('admin.users.mass_destroy') }}';
        @endcan
        
    </script>
@endsection