routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });


Route::get('/product-list/{id?}', 'WebpageController@product_list');

Route::get('/product-detail/{id}', 'WebpageController@product_detail');

Route::post('/product-filter', 'WebpageController@product_filter');

Route::post('/product-view-all', 'WebpageController@product_view_all');

Route::get('/product-price-filter', 'WebpageController@product_price_filter');


Route::get('/about-us', 'WebpageController@about_us');

Route::get('/contact-us', 'WebpageController@contact_us');

Route::post('/sendingemail', 'WebpageController@sendEmail');

Route::get('/promotion', 'WebpageController@promotion');

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);

    Route::resource('collection', 'Admin\CollectionController');

    Route::resource('product', 'Admin\ProductController');

    Route::get('delete_image/{image_id}/{product_id}', 'Admin\ProductController@deleteImage');

    Route::resource('about', 'Admin\AboutController');

    Route::resource('promotion', 'Admin\PromotionController');

});

app/Collection.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Collection extends Model
{

    public function product() {
    	return $this->hasMany('App\Product', 'category_id');
    }
}

app/Http/Controllers/Admin/CollectionController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Http\Requests;
use App\Collection;
use App\Product;
use Illuminate\Foundation\Validation\ValidatesRequests;

class CollectionController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $collections = Collection::all();
        $count_set_home = Collection::where('show_front_end','yes')->get()->count();
        return view('admin.collection.index', compact(['collections','count_set_home']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $main_categories = Collection::whereNull('sub_collection')->get();
        return view('admin.collection.create',compact(['main_categories']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required'
        ]);

        $collection = new Collection();
        $collection->name = $request->name;
        $collection->type = $request->is_collection;
        if ($request->sub_category != null) {
            $collection->sub_collection = $request->sub_category;
        }
        $collection->save();
        return redirect('/admin/collection');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $collections = Collection::find($id);
        return view('admin.collection.view',compact(['collections']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $collection = Collection::find($id);
        $main_categories = Collection::whereNull('sub_collection')->get();
        return view('admin.collection.edit',compact(['collection','main_categories']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        //dd($id);
        $collection = Collection::find($id);
        $collection->name = $request->name;
        $collection->type = $request->is_collection;
        if ($request->sub_category != null) {
            $collection->sub_collection = $request->sub_category;
        }
        $collection->save();
        return redirect('/admin/collection');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $collection = Collection::find($id);
        $collection->delete();
        $product = Product::where('category_id',$id)->get();
        
        if (count($product)>0) {            
            Product::where('category_id',$id)->delete();
        } 
        
        return redirect('/admin/collection');
    }

    public function setHome($id)
    {
        $category = Collection::where('id',$id)->value('show_front_end');
        $result = '';
            $collection = Collection::find($id);
        if ($category == 'yes') {
            $collection->show_front_end = null;
            $result = - 1;
        }else{
            $collection->show_front_end = 'yes';
            $result = + 1;
        }
            $collection->save();

        return $result;
    }
}

resources/views/admin/collection/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">Category</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.collection.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            Create
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
					<ul id="tree1">
						@foreach($main_categories as $main)
						<?php 
						$sub_cat = App\Collection::where('sub_collection',$main->id)->get();
						?>
						@if(count($sub_cat)>0)

						<li><a href="#" id="{{$main->id}}" class="radio-value">{{$main->name}}</a>
							<ul>
								@foreach($sub_cat as $sub)
								<?php 
								$inner_cat = App\Collection::where('sub_collection',$sub->id)->get();
								?>
								@if(count($inner_cat)>0)
								<li><a href="#" id="{{$main->id}}" class="radio-value">
									{{$sub->name}}</a>
									<ul>
										@foreach($inner_cat as $cat)
										<li>
											<a href="#">
												<div class="radio-success radio ">
													<input type="radio" name="is_available" id="{{$cat->id}}" value="{{$cat->name}}" >
													<label for="{{$cat->id}}" id="{{$cat->id}}"  class="radio-value">{{$cat->name}}
													</label>
												</div>
											</a>
										</li>
										@endforeach
									</ul>
								</li>
								@else
								<li>
									<a href="#">
										<div class="radio-success radio ">
											<input type="radio" name="is_available" id="{{$sub->id}}" value="{{$sub->name}}" >
											<label for="{{$sub->id}}" id="{{$sub->id}}"  class="radio-value">{{$sub->name}}
											</label>
										</div>
									</a>
								</li>
								@endif
								@endforeach
							</ul>
						</li>
						@else
						<li><a href="#">
							<div class="radio-success radio ">
								<input type="radio" name="is_available" id="{{$main->id}}" value="{{$main->name}}" >
								<label for="{{$main->id}}"  class="radio-value" id="{{$main->id}}">{{$main->name}}
								</label>
							</div>
						</a>

					</li>
					@endif
					@endforeach

				</ul>
				</div>
				<div class="col-md-6">
					
					<div class="form-group  category-info">

					</div>
					<div class="form-group" >
					<label class="control-label">Is Collection</label>
						<div class="row">
							<div class="col-md-2">												
								<div class="radio-primary radio">
									<input type="radio" name="is_collection" id="is_collection-0" value="yes">
									<label for="is_collection-0" style="padding-left: 5px;">Yes
									</label>
								</div>
							</div>
							<div class="col-md-10">
								<div class="radio-primary radio">
									<input type="radio" name="is_collection" id="is_collection-1" value="no" checked="checked">
									<label for="is_collection-1" style="padding-left: 5px;">No
									</label>
								</div>
							</div>
						</div>
					</div>
					<div class="form-group  is-empty">
						<label  class="control-label">Category Name</label>
						<input type="text" class="form-control"  required="" name="name">
						<input type="hidden" name="sub_category" id="sub_category">
						<span class="help-block">
							<!-- Enter product name. -->
						</span>
					</div>
				</div>
            </div>
            
            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

@section('javascript')
<script>

	$(document).ready(function(){
		$('.radio-value').click(function () {
			$('.radio-value').removeClass('text-success');
			var id = this.id;
			//alert(id);
			$('.category-info').empty();
			var value = $(this).text();
			$(this).addClass('text-success');
			$('.category-info').append('<label  class="control-label text-success" id="label'+id+'">This category name will be under '+value+'.</label> <span class="remove pull-right btn btn-xs btn-danger" id="'+id+'">Remove</span>');
			$('#sub_category').val(id);
			$('.indicator').removeClass('text-success');
			$('input[type=radio]').removeAttr('checked'); 
			$(this).parent().find('.glyphicon-minus-sign').addClass('text-success');
		});

		$(document).on('click', '.remove', function(){
			var id = this.id;
			$('label[id=label'+id+']').remove();
			$('.category-info').append('<label class="control-label text-info">Parent Category Removed.</label>');
			$('#sub_category').val(null);
			this.remove();
		});

	});

	$.fn.extend({
		treed: function (o) {

			var openedClass = 'glyphicon-minus-sign';
			var closedClass = 'glyphicon-plus-sign';

			if (typeof o != 'undefined'){
				if (typeof o.openedClass != 'undefined'){
					openedClass = o.openedClass;
				}
				if (typeof o.closedClass != 'undefined'){
					closedClass = o.closedClass;
				}
			};

        //initialize each of the top levels
        var tree = $(this);
        tree.addClass("tree");
        tree.find('li').has("ul").each(function () {
            var branch = $(this); //li with children ul
            branch.prepend("<i class='indicator glyphicon " + closedClass + "'></i>");
            branch.addClass('branch');
            branch.on('click', function (e) {
            	if (this == e.target) {
            		var icon = $(this).children('i:first');
            		icon.toggleClass(openedClass + " " + closedClass);
            		$(this).children().children().toggle();
            	}
            })
            branch.children().children().toggle();
        });
        //fire event from the dynamically added icon
        tree.find('.branch .indicator').each(function(){
        	$(this).on('click', function () {
        		$(this).closest('li').click();
        	});
        });
        //fire event to open branch if the li contains an anchor instead of text
        tree.find('.branch>a').each(function () {
        	$(this).on('click', function (e) {
        		$(this).closest('li').click();
        		e.preventDefault();
        	});
        });
        //fire event to open branch if the li contains a button instead of text
        tree.find('.branch>button').each(function () {
        	$(this).on('click', function (e) {
        		$(this).closest('li').click();
        		e.preventDefault();
        	});
        });
    }
});

//Initialization of treeviews

$('#tree1').treed();



</script>
@stop

resources/views/admin/collection/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">Category</h3>
    {!! Form::model($collection, ['method' => 'PUT', 'route' => ['admin.collection.update', $collection->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            Create
        </div>
        
        <div class="panel-body">
            <div class="row">
					<div class="col-md-6">
						<ul id="tree1">
							@foreach($main_categories as $main)
							<?php 
							$sub_cat = App\Collection::where('sub_collection',$main->id)->get();
							?>
							@if(count($sub_cat)>0)

							<li><a href="#" id="{{$main->id}}" class="radio-value">{{$main->name}}</a>
								<ul>
									@foreach($sub_cat as $sub)
									<?php 
									$inner_cat = App\Collection::where('sub_collection',$sub->id)->get();
									?>
									@if(count($inner_cat)>0)
									<li><a href="#" id="{{$sub->id}}" class="radio-value">
										{{$sub->name}}</a>
										<ul>
											@foreach($inner_cat as $cat)
											<li>
												<a href="#">
													<div class="radio-success radio ">
														<input type="radio" name="is_available" id="{{$cat->id}}" value="{{$cat->name}}" >
														<label for="{{$cat->id}}" id="{{$cat->id}}"  class="radio-value">{{$cat->name}}
														</label>
													</div>
												</a>
											</li>
											@endforeach
										</ul>
									</li>
									@else
									<li>
										<a href="#">
											<div class="radio-success radio ">
												<input type="radio" name="is_available" id="{{$sub->id}}" value="{{$sub->name}}" >
												<label for="{{$sub->id}}" id="{{$sub->id}}"  class="radio-value">{{$sub->name}}
												</label>
											</div>
										</a>
									</li>
									@endif
									@endforeach
								</ul>
							</li>
							@else
							<li><a href="#">
								<div class="radio-success radio ">
									<input type="radio" name="is_available" id="{{$main->id}}" value="{{$main->name}}" >
									<label for="{{$main->id}}"  class="radio-value" id="{{$main->id}}">{{$main->name}}
									</label>
								</div>
							</a>

						</li>
						@endif
						@endforeach

					</ul>
				</div>
				<div class="col-md-6">
					<div class="form-group  category-info">

					</div>
					<div class="form-group" >
						<label class="control-label">Is Collection</label>
						<div class="row">
							<div class="col-md-2">	
								<div class="radio-primary radio">
									<input type="radio" name="is_collection" id="is_collection-0" value="yes" {{$collection->type == 'yes' ? 'checked' : ''}}>
									<label for="is_collection-0" style="padding-left: 5px;">Yes
									</label>
								</div>
							</div>
							<div class="col-md-10">
								<div class="radio-primary radio">
									<input type="radio" name="is_collection" id="is_collection-1" value="no" {{$collection->type == 'no' ? 'checked' : ''}}>
									<label for="is_collection-1" style="padding-left: 5px;">No
									</label>
								</div>
							</div>
						</div>
					</div>
					<div class="form-group  is-empty">
						<label  class="control-label">Category Name</label>
						<input type="text" class="form-control"  required="" name="name" value="{{$collection->name}}">
						<input type="hidden" name="sub_category" id="sub_category">
						<span class="help-block">
							<!-- Enter product name. -->
						</span>
					</div>
				</div>
			</div>
		</div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

@section('javascript')
<script>

	$(document).ready(function(){
		$('.radio-value').click(function () {
			$('.radio-value').removeClass('text-success');
			var id = this.id;
			//alert(id);
			$('.category-info').empty();
			var value = $(this).text();
			$(this).addClass('text-success');
			$('.category-info').append('<label  class="control-label text-success" id="label'+id+'">This category name will be under '+value+'.</label> <span class="remove pull-right btn btn-xs btn-danger" id="'+id+'">Remove</span>');
			$('#sub_category').val(id);
			$('.indicator').removeClass('text-success');
			$('input[type=radio]').removeAttr('checked'); 
			$(this).parent().find('.glyphicon-minus-sign').addClass('text-success');
		});

		$(document).on('click', '.remove', function(){
			var id = this.id;
			$('label[id=label'+id+']').remove();
			$('.category-info').append('<label class="control-label text-info">Parent Category Removed.</label>');
			$('#sub_category').val(null);
			this.remove();
		});

	});

	$.fn.extend({
		treed: function (o) {

			var openedClass = 'glyphicon-minus-sign';
			var closedClass = 'glyphicon-plus-sign';

			if (typeof o != 'undefined'){
				if (typeof o.openedClass != 'undefined'){
					openedClass = o.openedClass;
				}
				if (typeof o.closedClass != 'undefined'){
					closedClass = o.closedClass;
				}
			};

        //initialize each of the top levels
        var tree = $(this);
        tree.addClass("tree");
        tree.find('li').has("ul").each(function () {
            var branch = $(this); //li with children ul
            branch.prepend("<i class='indicator glyphicon " + closedClass + "'></i>");
            branch.addClass('branch');
            branch.on('click', function (e) {
            	if (this == e.target) {
            		var icon = $(this).children('i:first');
            		icon.toggleClass(openedClass + " " + closedClass);
            		$(this).children().children().toggle();
            	}
            })
            branch.children().children().toggle();
        });
        //fire event from the dynamically added icon
        tree.find('.branch .indicator').each(function(){
        	$(this).on('click', function () {
        		$(this).closest('li').click();
        	});
        });
        //fire event to open branch if the li contains an anchor instead of text
        tree.find('.branch>a').each(function () {
        	$(this).on('click', function (e) {
        		$(this).closest('li').click();
        		e.preventDefault();
        	});
        });
        //fire event to open branch if the li contains a button instead of text
        tree.find('.branch>button').each(function () {
        	$(this).on('click', function (e) {
        		$(this).closest('li').click();
        		e.preventDefault();
        	});
        });
    }
});

//Initialization of treeviews

$('#tree1').treed();



</script>
@stop

resources/views/admin/collection/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">Category</h3>
    <p>
        <a href="{{ route('admin.collection.create') }}" class="btn btn-success">Create</a>        
    </p>    

    <div class="panel panel-default">
        <div class="panel-heading">
            List
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($collections) > 0 ? 'datatable' : '' }}">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                
                <tbody>
                    @if (count($collections) > 0)
                        @foreach ($collections as $collection)
                            <tr data-entry-id="{{ $collection->id }}">

                                <td field-key='name'>{{ $collection->name }}</td>
                                <td>
                                    <a href="{{ route('admin.collection.show',[$collection->id]) }}" class="btn btn-xs btn-primary">View</a>                                    
                                    <a href="{{ route('admin.collection.edit',[$collection->id]) }}" class="btn btn-xs btn-info">Edit</a>
									{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.collection.destroy', $collection->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                </td>

                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="10">@lang('quickadmin.qa_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('user_delete')
            window.route_mass_crud_entries_destroy = '{{ route('admin.users.mass_destroy') }}';
        @endcan

    </script>
@endsection

resources/views/admin/collection/view.blade.php
@extends('admin.header')
@section('content')
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="dashboard_graph">
			<div class="row">
				<div class="col-md-12 x_title col-xs-12">
					<h2>View Category</h2>
					
				</div>
				
			</div>
			
				<div class="row">
					<div class="col-md-6">

						<div class="form-group  is-empty">
							<label  class="control-label">Category Name</label>
							<input type="text" class="form-control"  required="" name="name" value="{{$collections->name}}" readonly="">
							<span class="help-block">
								<!-- Enter product name. -->
							</span>
						</div>
	
					</div>

					
				</div>

				<div class=" row">
					<div class="col-md-6">
						<a href="{{asset('/admin/collection')}}" class="btn btn-info">Cancel</a>
						<a href="{{asset('/admin/collection/'.$collections->id.'/edit')}}" class="btn btn-warning pull-right"><i class="fa fa-edit"></i> Edit</a>
						
					</div>
				</div>

			
		</div>
	</div>

</div>
@endsection